FROM quay.io/fedora-ostree-desktops/sericea:rawhide as pyrite

RUN curl -Lo /etc/yum.repos.d/_copr_kylegospo-steamdeck-kmod.repo https://copr.fedorainfracloud.org/coprs/kylegospo/steamdeck-kmod/repo/fedora-rawhide/kylegospo-steamdeck-kmod-fedora-rawhide.repo \
  &&  ostree container commit


RUN rpm-ostree install akmods && ostree container commit
RUN ls /usr && echo "---------------" && ls /usr/bin
RUN rpm-ostree install \
  steamdeck \
  steamdeck-kmod && \
   ostree container commit

